"""empty message

Revision ID: 0005186d799f
Revises: ae41f76cde70
Create Date: 2026-02-27 21:12:06.113218

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0005186d799f'
down_revision = 'ae41f76cde70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.drop_column('strategic_weight')
        batch_op.drop_column('support_weight')
        batch_op.drop_column('core_weight')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('core_weight', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('support_weight', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('strategic_weight', mysql.FLOAT(), nullable=True))

    # ### end Alembic commands ###
