"""empty message

Revision ID: 0523a53c752c
Revises: de50f8e4156f
Create Date: 2025-10-23 21:45:26.682236

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0523a53c752c'
down_revision = 'de50f8e4156f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ipcr', schema=None) as batch_op:
        batch_op.drop_column('form_status')

    with op.batch_alter_table('opcr', schema=None) as batch_op:
        batch_op.drop_column('form_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opcr', schema=None) as batch_op:
        batch_op.add_column(sa.Column('form_status', mysql.ENUM('draft', 'pending', 'approved', 'rejected', 'archived'), nullable=True))

    with op.batch_alter_table('ipcr', schema=None) as batch_op:
        batch_op.add_column(sa.Column('form_status', mysql.ENUM('draft', 'pending', 'reviewed', 'approved', 'rejected', 'archived'), nullable=True))

    # ### end Alembic commands ###
