"""added more columns in logs

Revision ID: 05db6725c37b
Revises: 5aacb855b137
Create Date: 2025-09-25 22:00:44.888880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05db6725c37b'
down_revision = '5aacb855b137'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ipcr', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isMain', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('form_status', sa.Enum('pending', 'reviewed', 'approved'), nullable=True))

    with op.batch_alter_table('opcr', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isMain', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('form_status', sa.Enum('pending', 'reviewed', 'approved'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opcr', schema=None) as batch_op:
        batch_op.drop_column('form_status')
        batch_op.drop_column('status')
        batch_op.drop_column('isMain')

    with op.batch_alter_table('ipcr', schema=None) as batch_op:
        batch_op.drop_column('form_status')
        batch_op.drop_column('status')
        batch_op.drop_column('isMain')

    # ### end Alembic commands ###
