"""empty message

Revision ID: 079eeb1bf9da
Revises: d3d4da5be40f
Create Date: 2026-04-18 00:23:12.845391

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '079eeb1bf9da'
down_revision = 'd3d4da5be40f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submitted_by', sa.Integer(), nullable=False),
    sa.Column('task_blueprint', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('values', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_blueprint'], ['form_submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('task_submissions')
    op.drop_table('user_submissions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_submissions',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('template_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('submitted_by', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('submission_date', mysql.DATETIME(), nullable=True),
    sa.Column('is_draft', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], name=op.f('user_submissions_ibfk_2')),
    sa.ForeignKeyConstraint(['template_id'], ['form_templates.id'], name=op.f('user_submissions_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('task_submissions',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('template_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('submitted_by', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('submission_date', mysql.DATETIME(), nullable=True),
    sa.Column('is_draft', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], name=op.f('task_submissions_ibfk_2')),
    sa.ForeignKeyConstraint(['template_id'], ['form_templates.id'], name=op.f('task_submissions_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('task_responses')
    # ### end Alembic commands ###
