"""added more columns in logs

Revision ID: 07f03532d85c
Revises: 391c72f8f868
Create Date: 2025-09-23 17:20:35.711184

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '07f03532d85c'
down_revision = '391c72f8f868'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sub_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_acc', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('target_time', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('target_mod', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('actual_acc', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('actual_time', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('actual_mod', sa.Integer(), nullable=False))
        batch_op.drop_column('target_time_description_value')
        batch_op.drop_column('target_accomplishment')
        batch_op.drop_column('actual_time_description')
        batch_op.drop_column('target_modification_value')
        batch_op.drop_column('actual_modification_value')
        batch_op.drop_column('target_accomplishment_value')
        batch_op.drop_column('actual_time_description_value')
        batch_op.drop_column('actual_accomplishment')
        batch_op.drop_column('actual_accomplishment_value')
        batch_op.drop_column('actual_modification')
        batch_op.drop_column('target_time_description')
        batch_op.drop_column('target_modification')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sub_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_modification', mysql.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('target_time_description', mysql.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('actual_modification', mysql.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('actual_accomplishment_value', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('actual_accomplishment', mysql.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('actual_time_description_value', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('target_accomplishment_value', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('actual_modification_value', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('target_modification_value', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('actual_time_description', mysql.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('target_accomplishment', mysql.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('target_time_description_value', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('actual_mod')
        batch_op.drop_column('actual_time')
        batch_op.drop_column('actual_acc')
        batch_op.drop_column('target_mod')
        batch_op.drop_column('target_time')
        batch_op.drop_column('target_acc')

    # ### end Alembic commands ###
