"""added pcr and departments

Revision ID: 0ab83d2f9831
Revises: 052ae3da1dbc
Create Date: 2025-09-11 16:51:16.388445

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0ab83d2f9831'
down_revision = '052ae3da1dbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('main_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'departments', ['department_id'], ['id'])

    with op.batch_alter_table('sub_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('efficiency', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('timeliness', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('average', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ipcr_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('sub_tasks_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'ipcr', ['ipcr_id'], ['id'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'departments', ['department_id'], ['id'])
        batch_op.drop_column('department')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department', mysql.VARCHAR(length=50), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('department_id')

    with op.batch_alter_table('sub_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('sub_tasks_ibfk_2'), 'users', ['user_id'], ['id'])
        batch_op.drop_column('ipcr_id')
        batch_op.drop_column('average')
        batch_op.drop_column('timeliness')
        batch_op.drop_column('efficiency')
        batch_op.drop_column('quantity')

    with op.batch_alter_table('main_tasks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('department_id')

    # ### end Alembic commands ###
