"""added more columns in logs

Revision ID: 0b450f7206dc
Revises: 7ac447c2d1a4
Create Date: 2025-09-29 14:15:57.344242

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0b450f7206dc'
down_revision = '7ac447c2d1a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supporting_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_type', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('file_name', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ipcr', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('batch_id', sa.Text(), nullable=True))
        batch_op.create_foreign_key(None, 'ipcr', ['ipcr'], ['id'])
        batch_op.drop_column('approved_by')
        batch_op.drop_column('reviewed_by')
        batch_op.drop_column('discussed_with')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supporting_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discussed_with', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('reviewed_by', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('approved_by', mysql.TEXT(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('batch_id')
        batch_op.drop_column('ipcr')
        batch_op.drop_column('file_name')
        batch_op.drop_column('file_type')

    # ### end Alembic commands ###
