"""empty message

Revision ID: 0c7b23e98852
Revises: 8d5e900751c3
Create Date: 2026-03-01 15:11:16.253204

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0c7b23e98852'
down_revision = '8d5e900751c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alert_thresholds', mysql.JSON(), nullable=True))
        batch_op.add_column(sa.Column('kpi_definitions', mysql.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_column('kpi_definitions')
        batch_op.drop_column('alert_thresholds')

    # ### end Alembic commands ###
