"""empty message

Revision ID: 0cc86fd48a0f
Revises: 6d7b528fc968
Create Date: 2025-12-05 17:00:39.707919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cc86fd48a0f'
down_revision = '6d7b528fc968'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('main_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_quantity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('target_efficiency', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('deadline_start', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('target_timeframe', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('timeliness_mode', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('main_tasks', schema=None) as batch_op:
        batch_op.drop_column('timeliness_mode')
        batch_op.drop_column('target_timeframe')
        batch_op.drop_column('deadline_start')
        batch_op.drop_column('target_efficiency')
        batch_op.drop_column('target_quantity')

    # ### end Alembic commands ###
