"""added more columns in logs

Revision ID: 12b439374d98
Revises: bd72e19ba00c
Create Date: 2025-09-23 11:37:40.326559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12b439374d98'
down_revision = 'bd72e19ba00c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('output', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sub_task_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'sub_tasks', ['sub_task_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('output', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('sub_task_id')

    # ### end Alembic commands ###
