"""empty message

Revision ID: 147f55a63b1d
Revises: 1dc260bcab7c
Create Date: 2025-10-23 21:42:34.424011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '147f55a63b1d'
down_revision = '1dc260bcab7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ipcr', schema=None) as batch_op:
        batch_op.add_column(sa.Column('form_status', sa.Enum('draft', 'pending', 'reviewed', 'approved', 'rejected', 'archived'), nullable=True))

    with op.batch_alter_table('opcr', schema=None) as batch_op:
        batch_op.add_column(sa.Column('form_status', sa.Enum('draft', 'pending', 'approved', 'rejected', 'archived'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opcr', schema=None) as batch_op:
        batch_op.drop_column('form_status')

    with op.batch_alter_table('ipcr', schema=None) as batch_op:
        batch_op.drop_column('form_status')

    # ### end Alembic commands ###
