"""empty message

Revision ID: 15cdac89a58e
Revises: adb3e73f0fb1
Create Date: 2026-02-21 21:39:01.513475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15cdac89a58e'
down_revision = 'adb3e73f0fb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assigned_departments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('efficiency', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('timeliness', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assigned_departments', schema=None) as batch_op:
        batch_op.drop_column('timeliness')
        batch_op.drop_column('efficiency')
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
