"""added recovery_email and 2fa

Revision ID: 1ea9f8c7d3b5
Revises: f1508c9306a7
Create Date: 2026-01-15 10:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ea9f8c7d3b5'
down_revision = 'f1508c9306a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recovery_email', sa.String(255), nullable=True))
        batch_op.add_column(sa.Column('two_factor_enabled', sa.Boolean(), default=False, nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('two_factor_enabled')
        batch_op.drop_column('recovery_email')

    # ### end Alembic commands ###
