"""empty message

Revision ID: 29a00363c7c9
Revises: 49e6c1c6cdd5
Create Date: 2025-12-01 21:06:30.551047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29a00363c7c9'
down_revision = '49e6c1c6cdd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_period', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('planning_start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('planning_end_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('monitoring_start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('monitoring_end_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('rating_start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('rating_end_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_column('rating_end_date')
        batch_op.drop_column('rating_start_date')
        batch_op.drop_column('monitoring_end_date')
        batch_op.drop_column('monitoring_start_date')
        batch_op.drop_column('planning_end_date')
        batch_op.drop_column('planning_start_date')
        batch_op.drop_column('current_period')

    # ### end Alembic commands ###
