"""removed the relationship between dept and maintask

Revision ID: 2b680634bf97
Revises: b6c5a3cf2e99
Create Date: 2025-09-11 22:40:07.348184

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2b680634bf97'
down_revision = 'b6c5a3cf2e99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('main_tasks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('main_tasks_ibfk_2'), type_='foreignkey')
        batch_op.drop_column('department_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('main_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('main_tasks_ibfk_2'), 'departments', ['department_id'], ['id'])

    # ### end Alembic commands ###
