"""added status to category

Revision ID: 2c63309e3bcb
Revises: 703f20a0a45f
Create Date: 2025-09-16 11:51:38.187294

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2c63309e3bcb'
down_revision = '703f20a0a45f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('main_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_description', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('modification', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('time_taken', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('modifications', sa.Integer(), nullable=False))
        batch_op.drop_column('actual_modification')
        batch_op.drop_column('target_time_description')
        batch_op.drop_column('target_modification')
        batch_op.drop_column('actual_time_description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('main_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actual_time_description', mysql.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('target_modification', mysql.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('target_time_description', mysql.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('actual_modification', mysql.TEXT(), nullable=False))
        batch_op.drop_column('modifications')
        batch_op.drop_column('time_taken')
        batch_op.drop_column('modification')
        batch_op.drop_column('time_description')

    # ### end Alembic commands ###
