"""added more columns in logs

Revision ID: 2ed7b290240f
Revises: d15e3aeabc1c
Create Date: 2025-09-29 14:29:10.565000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ed7b290240f'
down_revision = 'd15e3aeabc1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supporting_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supporting_documents', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
