"""added more columns in logs

Revision ID: 3198516f680b
Revises: 2fc12e6a7d81
Create Date: 2025-10-10 19:51:21.312895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3198516f680b'
down_revision = '2fc12e6a7d81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ipcr', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rev_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('app_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('dis_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('ass_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('fin_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('con_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('opcr', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rev_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('app_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('dis_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('ass_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('fin_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('con_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opcr', schema=None) as batch_op:
        batch_op.drop_column('con_date')
        batch_op.drop_column('fin_date')
        batch_op.drop_column('ass_date')
        batch_op.drop_column('dis_date')
        batch_op.drop_column('app_date')
        batch_op.drop_column('rev_date')

    with op.batch_alter_table('ipcr', schema=None) as batch_op:
        batch_op.drop_column('con_date')
        batch_op.drop_column('fin_date')
        batch_op.drop_column('ass_date')
        batch_op.drop_column('dis_date')
        batch_op.drop_column('app_date')
        batch_op.drop_column('rev_date')

    # ### end Alembic commands ###
