"""empty message

Revision ID: 31cd906c0755
Revises: 192e249b4bb6
Create Date: 2026-03-02 22:15:24.750168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31cd906c0755'
down_revision = '192e249b4bb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assigned_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_time', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('assigned_mod', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assigned_tasks', schema=None) as batch_op:
        batch_op.drop_column('assigned_mod')
        batch_op.drop_column('assigned_time')

    # ### end Alembic commands ###
