"""hehe

Revision ID: 353234410a0e
Revises: 9bcdc72b5be9
Create Date: 2025-11-22 12:52:44.368110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '353234410a0e'
down_revision = '9bcdc72b5be9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
