"""added more columns in logs

Revision ID: 391c72f8f868
Revises: ef95242ae3c5
Create Date: 2025-09-23 13:00:59.807882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '391c72f8f868'
down_revision = 'ef95242ae3c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outputs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isAssigned', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outputs', schema=None) as batch_op:
        batch_op.drop_column('isAssigned')

    # ### end Alembic commands ###
