"""empty message

Revision ID: 3c834288053c
Revises: d2217103a165
Create Date: 2026-01-04 10:54:11.345904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c834288053c'
down_revision = 'd2217103a165'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assigned_departments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enable_formulas', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assigned_departments', schema=None) as batch_op:
        batch_op.drop_column('enable_formulas')

    # ### end Alembic commands ###
