"""added more columns in logs

Revision ID: 3f86a675a080
Revises: 4fe4be279141
Create Date: 2025-10-05 10:21:21.003134

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3f86a675a080'
down_revision = '4fe4be279141'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.Enum('faculty', 'head', 'president', 'administrator'), nullable=True))
        batch_op.drop_column('roles')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('roles', mysql.ENUM('faculty', 'head', 'president', 'administrator'), nullable=True))
        batch_op.drop_column('role')

    # ### end Alembic commands ###
