"""empty message

Revision ID: 40314679f0f4
Revises: 079eeb1bf9da
Create Date: 2026-04-18 10:27:30.860461

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '40314679f0f4'
down_revision = '079eeb1bf9da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_responses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('task_responses_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tasks', ['task_id'], ['id'])
        batch_op.drop_column('task_blueprint')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('template_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('created_by',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('created_by',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('template_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('task_responses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_blueprint', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('task_responses_ibfk_2'), 'form_submissions', ['task_blueprint'], ['id'])
        batch_op.drop_column('task_id')

    # ### end Alembic commands ###
