"""empty message

Revision ID: 486b5030bf87
Revises: 6320aa3babde
Create Date: 2026-01-08 00:06:37.304808

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '486b5030bf87'
down_revision = '6320aa3babde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority_order', sa.Integer(), nullable=True))

    with op.batch_alter_table('main_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.drop_constraint(batch_op.f('main_tasks_ibfk_2'), type_='foreignkey')
        batch_op.drop_column('department_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('main_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('main_tasks_ibfk_2'), 'departments', ['department_id'], ['id'])
        batch_op.drop_column('description')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('priority_order')

    # ### end Alembic commands ###
