"""empty message

Revision ID: 49e6c1c6cdd5
Revises: e5ab3819178a
Create Date: 2025-12-01 21:00:13.088198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49e6c1c6cdd5'
down_revision = 'e5ab3819178a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_president_fullname', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('current_mayor_fullname', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_column('current_mayor_fullname')
        batch_op.drop_column('current_president_fullname')

    # ### end Alembic commands ###
