"""added revision

Revision ID: 4d4416e20a6a
Revises: a79eb567f0e6
Create Date: 2025-10-19 14:18:09.262338

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4d4416e20a6a'
down_revision = 'a79eb567f0e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ipcr', schema=None) as batch_op:
        batch_op.drop_column('form_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ipcr', schema=None) as batch_op:
        batch_op.add_column(sa.Column('form_status', mysql.ENUM('pending', 'reviewed', 'approved', 'rejected', 'archived'), nullable=True))

    # ### end Alembic commands ###
