"""added more columns in logs

Revision ID: 4fe4be279141
Revises: 9f420c9dbe4a
Create Date: 2025-10-05 10:21:11.018764

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4fe4be279141'
down_revision = '9f420c9dbe4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('roles', sa.Enum('faculty', 'head', 'president', 'administrator'), nullable=True))
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', mysql.ENUM('faculty', 'head', 'administrator'), nullable=True))
        batch_op.drop_column('roles')

    # ### end Alembic commands ###
