"""empty message

Revision ID: 547a9e0f3374
Revises: b5d686d3531b
Create Date: 2025-12-05 23:08:02.110116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '547a9e0f3374'
down_revision = 'b5d686d3531b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sub_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actual_deadline', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sub_tasks', schema=None) as batch_op:
        batch_op.drop_column('actual_deadline')

    # ### end Alembic commands ###
