"""empty message

Revision ID: 55121a1472c6
Revises: 0d053df2f9cd
Create Date: 2026-04-20 21:45:02.669297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55121a1472c6'
down_revision = '0d053df2f9cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supporting_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('relevance_justification', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supporting_documents', schema=None) as batch_op:
        batch_op.drop_column('relevance_justification')

    # ### end Alembic commands ###
