"""added more columns in logs

Revision ID: 5aacb855b137
Revises: 67f57c977169
Create Date: 2025-09-25 00:07:56.559757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5aacb855b137'
down_revision = '67f57c977169'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sub_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('batch_id', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sub_tasks', schema=None) as batch_op:
        batch_op.drop_column('batch_id')

    # ### end Alembic commands ###
