"""added more columns in logs

Revision ID: 5b4e0bb4e73e
Revises: a5ef3df6a84c
Create Date: 2025-10-03 09:56:32.782716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b4e0bb4e73e'
down_revision = 'a5ef3df6a84c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assigned_pcrs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'departments', ['department_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assigned_pcrs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('department_id')

    # ### end Alembic commands ###
