"""empty message

Revision ID: 63aedde53b84
Revises: 051878d59299
Create Date: 2026-04-17 13:24:24.999633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63aedde53b84'
down_revision = '051878d59299'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('column_mapping', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_templates', schema=None) as batch_op:
        batch_op.drop_column('column_mapping')

    # ### end Alembic commands ###
