"""added more columns in logs

Revision ID: 678f4a1718f2
Revises: c81cd0e780ed
Create Date: 2025-09-20 22:53:52.086926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '678f4a1718f2'
down_revision = 'c81cd0e780ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ip_address', sa.String(length=45), nullable=True))
        batch_op.add_column(sa.Column('user_agent', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.drop_column('user_agent')
        batch_op.drop_column('ip_address')
        batch_op.drop_column('description')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
