"""added more columns in logs

Revision ID: 67f57c977169
Revises: 68d0acc14214
Create Date: 2025-09-24 23:58:08.997025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67f57c977169'
down_revision = '68d0acc14214'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assigned_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('batch_id', sa.Text(), nullable=True))

    with op.batch_alter_table('outputs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('batch_id', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outputs', schema=None) as batch_op:
        batch_op.drop_column('batch_id')

    with op.batch_alter_table('assigned_tasks', schema=None) as batch_op:
        batch_op.drop_column('batch_id')

    # ### end Alembic commands ###
