"""removed the relationship between dept and maintask

Revision ID: 6b8369d863b6
Revises: a4169d9fcd03
Create Date: 2025-09-12 17:31:22.053738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b8369d863b6'
down_revision = 'a4169d9fcd03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_column('icon')

    # ### end Alembic commands ###
