"""added revision

Revision ID: 6c7428321af0
Revises: 8b3f2e4f4e7c
Create Date: 2025-10-19 10:10:29.364785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c7428321af0'
down_revision = '8b3f2e4f4e7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ipcr', schema=None) as batch_op:
        batch_op.add_column(sa.Column('form_status', sa.Enum('pending', 'reviewed', 'approved', 'rejected', 'archived'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ipcr', schema=None) as batch_op:
        batch_op.drop_column('form_status')

    # ### end Alembic commands ###
