"""added status to category

Revision ID: 703f20a0a45f
Revises: 7ba0c01ac9ad
Create Date: 2025-09-16 11:21:06.006471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '703f20a0a45f'
down_revision = '7ba0c01ac9ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('main_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accomplishment_editable', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('time_editable', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('modification_editable', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('main_tasks', schema=None) as batch_op:
        batch_op.drop_column('modification_editable')
        batch_op.drop_column('time_editable')
        batch_op.drop_column('accomplishment_editable')

    # ### end Alembic commands ###
