"""empty message

Revision ID: 706b4b9f30ff
Revises: eff5d0e56559
Create Date: 2026-04-02 22:35:09.147947

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '706b4b9f30ff'
down_revision = 'eff5d0e56559'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('login_otps')
    op.drop_table('task_metrics')
    with op.batch_alter_table('supporting_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isApproved', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supporting_documents', schema=None) as batch_op:
        batch_op.drop_column('isApproved')

    op.create_table('task_metrics',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('main_task_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('order', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('target_acc', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('acc_description', mysql.TEXT(), nullable=True),
    sa.Column('target_time', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('time_description', mysql.TEXT(), nullable=True),
    sa.Column('target_mod', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('mod_description', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['main_task_id'], ['main_tasks.id'], name=op.f('task_metrics_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('login_otps',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('otp_hash', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('salt', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('expires_at', mysql.DATETIME(), nullable=False),
    sa.Column('used', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('login_otps_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
