"""empty message

Revision ID: 70cb4a977a8c
Revises: ac986267620d
Create Date: 2025-12-27 10:26:01.265268

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '70cb4a977a8c'
down_revision = 'ac986267620d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assigned_departments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('period', sa.Text(), nullable=True))

    with op.batch_alter_table('main_tasks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('main_tasks_ibfk_2'), type_='foreignkey')
        batch_op.drop_column('department_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('main_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('main_tasks_ibfk_2'), 'departments', ['department_id'], ['id'])

    with op.batch_alter_table('assigned_departments', schema=None) as batch_op:
        batch_op.drop_column('period')

    # ### end Alembic commands ###
