"""hehe

Revision ID: 717fe6f9742c
Revises: 8af1fe5bf89d
Create Date: 2025-11-22 22:37:17.805877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '717fe6f9742c'
down_revision = '8af1fe5bf89d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
