"""empty message

Revision ID: 72ea48263792
Revises: ad20584a4b38
Create Date: 2025-11-30 11:18:37.762178

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '72ea48263792'
down_revision = 'ad20584a4b38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=50), nullable=True))
        batch_op.alter_column('name',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['name'])

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['name'])

    with op.batch_alter_table('main_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('require_documents', sa.Boolean(), nullable=True))

    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('core_weight', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('strategic_weight', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('support_weight', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.Integer(), nullable=True))

    with op.batch_alter_table('supporting_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sub_task_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'sub_tasks', ['sub_task_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supporting_documents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('sub_task_id')

    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('support_weight')
        batch_op.drop_column('strategic_weight')
        batch_op.drop_column('core_weight')

    with op.batch_alter_table('main_tasks', schema=None) as batch_op:
        batch_op.drop_column('require_documents')

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('name',
               existing_type=sa.String(length=50),
               type_=mysql.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('name',
               existing_type=sa.String(length=50),
               type_=mysql.TEXT(),
               existing_nullable=False)
        batch_op.drop_column('type')

    # ### end Alembic commands ###
