"""added more columns in logs

Revision ID: 785a6511616c
Revises: 3f86a675a080
Create Date: 2025-10-05 10:49:58.135328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '785a6511616c'
down_revision = '3f86a675a080'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ipcr', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rev_position', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('app_position', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('dis_position', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ass_position', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('fin_position', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('con_position', sa.Text(), nullable=True))

    with op.batch_alter_table('opcr', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rev_position', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('app_position', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('dis_position', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ass_position', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('fin_position', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('con_position', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opcr', schema=None) as batch_op:
        batch_op.drop_column('con_position')
        batch_op.drop_column('fin_position')
        batch_op.drop_column('ass_position')
        batch_op.drop_column('dis_position')
        batch_op.drop_column('app_position')
        batch_op.drop_column('rev_position')

    with op.batch_alter_table('ipcr', schema=None) as batch_op:
        batch_op.drop_column('con_position')
        batch_op.drop_column('fin_position')
        batch_op.drop_column('ass_position')
        batch_op.drop_column('dis_position')
        batch_op.drop_column('app_position')
        batch_op.drop_column('rev_position')

    # ### end Alembic commands ###
