"""empty message

Revision ID: 78fd5f0e8631
Revises: 0cc86fd48a0f
Create Date: 2025-12-05 17:51:04.811852

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '78fd5f0e8631'
down_revision = '0cc86fd48a0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('main_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_deadline', sa.DateTime(), nullable=True))
        batch_op.drop_column('deadline_start')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('main_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deadline_start', mysql.DATETIME(), nullable=True))
        batch_op.drop_column('target_deadline')

    # ### end Alembic commands ###
