"""added status in department

Revision ID: 7a386a3ad113
Revises: 15bbaacba415
Create Date: 2025-09-14 23:25:18.064442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a386a3ad113'
down_revision = '15bbaacba415'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('output', schema=None) as batch_op:
        batch_op.add_column(sa.Column('main_task_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'main_tasks', ['main_task_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('output', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('main_task_id')

    # ### end Alembic commands ###
