"""added more columns in logs

Revision ID: 7ac447c2d1a4
Revises: dc8548bdcb77
Create Date: 2025-09-28 22:57:21.513643

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7ac447c2d1a4'
down_revision = 'dc8548bdcb77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assigned_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Integer(), nullable=True))

    with op.batch_alter_table('outputs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Integer(), nullable=True))

    with op.batch_alter_table('sub_tasks', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sub_tasks', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)

    with op.batch_alter_table('outputs', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('assigned_tasks', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
