"""test

Revision ID: 822834e0d334
Revises: 3198516f680b
Create Date: 2025-10-15 22:20:32.993422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '822834e0d334'
down_revision = '3198516f680b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('full_name', sa.String(length=50), nullable=False),
    sa.Column('department', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('target', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('main_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mfo', sa.Text(), nullable=False),
    sa.Column('time_description', sa.Text(), nullable=False),
    sa.Column('modification', sa.Text(), nullable=False),
    sa.Column('target_accomplishment', sa.Text(), nullable=False),
    sa.Column('actual_accomplishment', sa.Text(), nullable=False),
    sa.Column('time_taken', sa.Integer(), nullable=False),
    sa.Column('modifications_done', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('assigned', sa.Boolean(), nullable=True),
    sa.Column('accomplishment_editable', sa.Boolean(), nullable=True),
    sa.Column('time_editable', sa.Boolean(), nullable=True),
    sa.Column('modification_editable', sa.Boolean(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opcr',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reviewed_by', sa.Text(), nullable=True),
    sa.Column('rev_position', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.Text(), nullable=True),
    sa.Column('app_position', sa.Text(), nullable=True),
    sa.Column('discussed_with', sa.Text(), nullable=True),
    sa.Column('dis_position', sa.Text(), nullable=True),
    sa.Column('assessed_by', sa.Text(), nullable=True),
    sa.Column('ass_position', sa.Text(), nullable=True),
    sa.Column('final_rating_by', sa.Text(), nullable=True),
    sa.Column('fin_position', sa.Text(), nullable=True),
    sa.Column('confirmed_by', sa.Text(), nullable=True),
    sa.Column('con_position', sa.Text(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('isMain', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('form_status', sa.Enum('pending', 'reviewed', 'approved'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('rev_date', sa.DateTime(), nullable=True),
    sa.Column('app_date', sa.DateTime(), nullable=True),
    sa.Column('dis_date', sa.DateTime(), nullable=True),
    sa.Column('ass_date', sa.DateTime(), nullable=True),
    sa.Column('fin_date', sa.DateTime(), nullable=True),
    sa.Column('con_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('middle_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('profile_picture_link', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('role', sa.Enum('faculty', 'head', 'president', 'administrator'), nullable=True),
    sa.Column('active_status', sa.Boolean(), nullable=True),
    sa.Column('account_status', sa.Integer(), nullable=True),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('managed_dept_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('assigned_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('main_task_id', sa.Integer(), nullable=True),
    sa.Column('is_assigned', sa.Boolean(), nullable=True),
    sa.Column('batch_id', sa.Text(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['main_task_id'], ['main_tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ipcr',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reviewed_by', sa.Text(), nullable=True),
    sa.Column('rev_position', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.Text(), nullable=True),
    sa.Column('app_position', sa.Text(), nullable=True),
    sa.Column('discussed_with', sa.Text(), nullable=True),
    sa.Column('dis_position', sa.Text(), nullable=True),
    sa.Column('assessed_by', sa.Text(), nullable=True),
    sa.Column('ass_position', sa.Text(), nullable=True),
    sa.Column('final_rating_by', sa.Text(), nullable=True),
    sa.Column('fin_position', sa.Text(), nullable=True),
    sa.Column('confirmed_by', sa.Text(), nullable=True),
    sa.Column('con_position', sa.Text(), nullable=True),
    sa.Column('rev_date', sa.DateTime(), nullable=True),
    sa.Column('app_date', sa.DateTime(), nullable=True),
    sa.Column('dis_date', sa.DateTime(), nullable=True),
    sa.Column('ass_date', sa.DateTime(), nullable=True),
    sa.Column('fin_date', sa.DateTime(), nullable=True),
    sa.Column('con_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('opcr_id', sa.Integer(), nullable=True),
    sa.Column('isMain', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('form_status', sa.Enum('pending', 'reviewed', 'approved'), nullable=True),
    sa.Column('batch_id', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['opcr_id'], ['opcr.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opcr_supporting_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.Text(), nullable=True),
    sa.Column('file_name', sa.Text(), nullable=True),
    sa.Column('opcr_id', sa.Integer(), nullable=True),
    sa.Column('batch_id', sa.Text(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['opcr_id'], ['opcr.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assigned_pcrs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ipcr_id', sa.Integer(), nullable=True),
    sa.Column('opcr_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['ipcr_id'], ['ipcr.id'], ),
    sa.ForeignKeyConstraint(['opcr_id'], ['opcr.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outputs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('main_task_id', sa.Integer(), nullable=True),
    sa.Column('ipcr_id', sa.Integer(), nullable=True),
    sa.Column('batch_id', sa.Text(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ipcr_id'], ['ipcr.id'], ),
    sa.ForeignKeyConstraint(['main_task_id'], ['main_tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supporting_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.Text(), nullable=True),
    sa.Column('file_name', sa.Text(), nullable=True),
    sa.Column('ipcr_id', sa.Integer(), nullable=True),
    sa.Column('batch_id', sa.Text(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ipcr_id'], ['ipcr.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sub_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mfo', sa.Text(), nullable=False),
    sa.Column('target_acc', sa.Integer(), nullable=True),
    sa.Column('target_time', sa.Integer(), nullable=True),
    sa.Column('target_mod', sa.Integer(), nullable=True),
    sa.Column('actual_acc', sa.Integer(), nullable=True),
    sa.Column('actual_time', sa.Integer(), nullable=True),
    sa.Column('actual_mod', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('efficiency', sa.Integer(), nullable=True),
    sa.Column('timeliness', sa.Integer(), nullable=True),
    sa.Column('average', sa.Integer(), nullable=True),
    sa.Column('output_id', sa.Integer(), nullable=True),
    sa.Column('main_task_id', sa.Integer(), nullable=True),
    sa.Column('ipcr_id', sa.Integer(), nullable=True),
    sa.Column('batch_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['ipcr_id'], ['ipcr.id'], ),
    sa.ForeignKeyConstraint(['main_task_id'], ['main_tasks.id'], ),
    sa.ForeignKeyConstraint(['output_id'], ['outputs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('output_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sub_tasks')
    op.drop_table('supporting_documents')
    op.drop_table('outputs')
    op.drop_table('assigned_pcrs')
    op.drop_table('opcr_supporting_documents')
    op.drop_table('notifications')
    op.drop_table('ipcr')
    op.drop_table('assigned_tasks')
    op.drop_table('users')
    op.drop_table('opcr')
    op.drop_table('main_tasks')
    op.drop_table('positions')
    op.drop_table('logs')
    op.drop_table('departments')
    op.drop_table('categories')
    # ### end Alembic commands ###
