"""added revision

Revision ID: 82af16b2ff89
Revises: 6c7428321af0
Create Date: 2025-10-19 10:12:31.470409

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '82af16b2ff89'
down_revision = '6c7428321af0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opcr', schema=None) as batch_op:
        batch_op.drop_column('form_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opcr', schema=None) as batch_op:
        batch_op.add_column(sa.Column('form_status', mysql.ENUM('pending', 'reviewed', 'approved'), nullable=True))

    # ### end Alembic commands ###
