"""added more columns in logs

Revision ID: 891583a4a1d0
Revises: 8d335bb176b6
Create Date: 2025-09-23 22:17:05.865638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '891583a4a1d0'
down_revision = '8d335bb176b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assigned_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assigned_tasks', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
