"""hehe

Revision ID: 8af1fe5bf89d
Revises: 353234410a0e
Create Date: 2025-11-22 14:01:01.344185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8af1fe5bf89d'
down_revision = '353234410a0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('core_weight', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('strategic_weight', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('support_weight', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.drop_column('support_weight')
        batch_op.drop_column('strategic_weight')
        batch_op.drop_column('core_weight')

    # ### end Alembic commands ###
