"""added revision

Revision ID: 8b3f2e4f4e7c
Revises: 977466b24a0e
Create Date: 2025-10-19 10:10:03.232050

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8b3f2e4f4e7c'
down_revision = '977466b24a0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ipcr', schema=None) as batch_op:
        batch_op.drop_column('form_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ipcr', schema=None) as batch_op:
        batch_op.add_column(sa.Column('form_status', mysql.ENUM('pending', 'reviewed', 'approved'), nullable=True))

    # ### end Alembic commands ###
