"""added more columns in logs

Revision ID: 8d335bb176b6
Revises: bce7c74f08df
Create Date: 2025-09-23 20:12:01.682373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d335bb176b6'
down_revision = 'bce7c74f08df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assigned_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_assigned', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assigned_tasks', schema=None) as batch_op:
        batch_op.drop_column('is_assigned')

    # ### end Alembic commands ###
