"""empty message

Revision ID: 8dc9791f207b
Revises: b45f18a4dffd
Create Date: 2026-05-20 10:53:39.198249

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8dc9791f207b'
down_revision = 'b45f18a4dffd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'profiles', ['profile_id'], ['id'])
        batch_op.drop_column('profile_picture_link')
        batch_op.drop_column('password')
        batch_op.drop_column('recovery_email')
        batch_op.drop_column('email')
        batch_op.drop_column('two_factor_enabled')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('two_factor_enabled', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('email', mysql.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('recovery_email', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('password', mysql.VARCHAR(length=250), nullable=False))
        batch_op.add_column(sa.Column('profile_picture_link', mysql.TEXT(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
