"""empty message

Revision ID: 95ccf553278a
Revises: 31cd906c0755
Create Date: 2026-03-03 21:32:16.750396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95ccf553278a'
down_revision = '31cd906c0755'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supporting_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('event_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('title', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supporting_documents', schema=None) as batch_op:
        batch_op.drop_column('title')
        batch_op.drop_column('description')
        batch_op.drop_column('event_date')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
