"""added more columns in logs

Revision ID: 966b389fe314
Revises: 678f4a1718f2
Create Date: 2025-09-21 23:00:06.551751

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '966b389fe314'
down_revision = '678f4a1718f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sub_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_accomplishment_value', sa.Integer(), nullable=True))
        batch_op.alter_column('target_accomplishment',
               existing_type=mysql.JSON(),
               type_=sa.Text(),
               nullable=False)
        batch_op.alter_column('target_time_description',
               existing_type=mysql.JSON(),
               type_=sa.Text(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sub_tasks', schema=None) as batch_op:
        batch_op.alter_column('target_time_description',
               existing_type=sa.Text(),
               type_=mysql.JSON(),
               nullable=True)
        batch_op.alter_column('target_accomplishment',
               existing_type=sa.Text(),
               type_=mysql.JSON(),
               nullable=True)
        batch_op.drop_column('target_accomplishment_value')

    # ### end Alembic commands ###
