"""added revision

Revision ID: 977466b24a0e
Revises: 822834e0d334
Create Date: 2025-10-19 10:07:37.412453

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '977466b24a0e'
down_revision = '822834e0d334'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ipcr', schema=None) as batch_op:
        batch_op.drop_column('form_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ipcr', schema=None) as batch_op:
        batch_op.add_column(sa.Column('form_status', mysql.ENUM('pending', 'reviewed', 'approved'), nullable=True))

    # ### end Alembic commands ###
