"""empty message

Revision ID: 9bcdc72b5be9
Revises: 93303ac46f38
Create Date: 2025-10-25 23:45:58.968474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bcdc72b5be9'
down_revision = '93303ac46f38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opcr_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mfo', sa.Text(), nullable=True),
    sa.Column('opcr_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('efficiency', sa.Integer(), nullable=True),
    sa.Column('timeliness', sa.Integer(), nullable=True),
    sa.Column('average', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['opcr_id'], ['opcr.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('opcr_ratings')
    # ### end Alembic commands ###
