"""added more columns in logs

Revision ID: 9f420c9dbe4a
Revises: 5b4e0bb4e73e
Create Date: 2025-10-05 10:05:28.350235

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9f420c9dbe4a'
down_revision = '5b4e0bb4e73e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department__rules')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department__rules',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('role', mysql.ENUM('deadline', 'filled'), nullable=True),
    sa.Column('icon', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
