"""added revision

Revision ID: a24f3bf23aa8
Revises: 6990b7c1d4a9
Create Date: 2025-10-20 23:05:46.545812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a24f3bf23aa8'
down_revision = '6990b7c1d4a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opcr', schema=None) as batch_op:
        batch_op.add_column(sa.Column('form_status', sa.Enum('draft', 'pending', 'approved', 'rejected', 'archived'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opcr', schema=None) as batch_op:
        batch_op.drop_column('form_status')

    # ### end Alembic commands ###
