"""removed the relationship between dept and maintask

Revision ID: a4169d9fcd03
Revises: 2b680634bf97
Create Date: 2025-09-12 17:28:23.482769

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a4169d9fcd03'
down_revision = '2b680634bf97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('departments_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('departments_ibfk_2'), type_='foreignkey')
        batch_op.drop_column('department_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('users_ibfk_3'), type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('users_ibfk_3'), 'departments', ['managed_dept_id'], ['id'])

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('departments_ibfk_2'), 'users', ['manager_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('departments_ibfk_1'), 'departments', ['department_id'], ['id'])

    # ### end Alembic commands ###
