"""added more columns in logs

Revision ID: a5ef3df6a84c
Revises: 60b5658d7506
Create Date: 2025-10-02 23:23:01.976954

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a5ef3df6a84c'
down_revision = '60b5658d7506'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assigned_ipcr')
    op.drop_table('assigned_pcr')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assigned_pcr',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ipcr_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('opcr_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ipcr_id'], ['ipcr.id'], name=op.f('assigned_pcr_ibfk_1')),
    sa.ForeignKeyConstraint(['opcr_id'], ['opcr.id'], name=op.f('assigned_pcr_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('assigned_ipcr',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ipcr_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('opcr_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ipcr_id'], ['ipcr.id'], name=op.f('assigned_ipcr_ibfk_1')),
    sa.ForeignKeyConstraint(['opcr_id'], ['opcr.id'], name=op.f('assigned_ipcr_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
