"""added revision

Revision ID: a79eb567f0e6
Revises: 82af16b2ff89
Create Date: 2025-10-19 10:13:35.612238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a79eb567f0e6'
down_revision = '82af16b2ff89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opcr', schema=None) as batch_op:
        batch_op.add_column(sa.Column('form_status', sa.Enum('pending', 'reviewed', 'approved', 'rejected', 'archived'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opcr', schema=None) as batch_op:
        batch_op.drop_column('form_status')

    # ### end Alembic commands ###
