"""hehe

Revision ID: ad20584a4b38
Revises: cc7cca8a3466
Create Date: 2025-11-27 22:39:48.771128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad20584a4b38'
down_revision = 'cc7cca8a3466'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supporting_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sub_task_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'sub_tasks', ['sub_task_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supporting_documents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('sub_task_id')

    # ### end Alembic commands ###
