"""empty message

Revision ID: ae41f76cde70
Revises: 15cdac89a58e
Create Date: 2026-02-27 21:10:42.629310

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ae41f76cde70'
down_revision = '15cdac89a58e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('opcr_ratings')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opcr_ratings',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('mfo', mysql.TEXT(), nullable=True),
    sa.Column('opcr_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('efficiency', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('timeliness', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('average', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('period', mysql.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['opcr_id'], ['opcr.id'], name=op.f('opcr_ratings_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
