"""hehe

Revision ID: b0d80b7ac300
Revises: d0391836a95e
Create Date: 2025-10-23 11:37:41.986055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0d80b7ac300'
down_revision = 'd0391836a95e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ipcr', schema=None) as batch_op:
        batch_op.add_column(sa.Column('form_status', sa.Enum('draft', 'pending', 'reviewed', 'approved', 'rejected', 'archived'), nullable=True))

    with op.batch_alter_table('opcr', schema=None) as batch_op:
        batch_op.add_column(sa.Column('form_status', sa.Enum('draft', 'pending', 'approved', 'rejected', 'archived'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opcr', schema=None) as batch_op:
        batch_op.drop_column('form_status')

    with op.batch_alter_table('ipcr', schema=None) as batch_op:
        batch_op.drop_column('form_status')

    # ### end Alembic commands ###
