"""empty message

Revision ID: b5d686d3531b
Revises: a7238a518d9a
Create Date: 2025-12-05 19:07:56.257441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5d686d3531b'
down_revision = 'a7238a518d9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outputs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_quantity', sa.Integer(), nullable=True))

    with op.batch_alter_table('sub_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_quantity', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sub_tasks', schema=None) as batch_op:
        batch_op.drop_column('assigned_quantity')

    with op.batch_alter_table('outputs', schema=None) as batch_op:
        batch_op.drop_column('assigned_quantity')

    # ### end Alembic commands ###
