"""added more columns in logs

Revision ID: bce7c74f08df
Revises: 07f03532d85c
Create Date: 2025-09-23 18:22:22.578029

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bce7c74f08df'
down_revision = '07f03532d85c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outputs', schema=None) as batch_op:
        batch_op.drop_column('isAssigned')

    with op.batch_alter_table('sub_tasks', schema=None) as batch_op:
        batch_op.alter_column('target_acc',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('target_time',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('target_mod',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('actual_acc',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('actual_time',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('actual_mod',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sub_tasks', schema=None) as batch_op:
        batch_op.alter_column('actual_mod',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('actual_time',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('actual_acc',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('target_mod',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('target_time',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('target_acc',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('outputs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isAssigned', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
