"""added more columns in logs

Revision ID: bd72e19ba00c
Revises: 966b389fe314
Create Date: 2025-09-23 11:21:26.360815

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bd72e19ba00c'
down_revision = '966b389fe314'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sub_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_time_description_value', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('target_modification_value', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('actual_accomplishment_value', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('actual_time_description_value', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('actual_modification_value', sa.Integer(), nullable=True))
        batch_op.alter_column('target_modification',
               existing_type=mysql.JSON(),
               type_=sa.Text(),
               nullable=False)
        batch_op.alter_column('actual_accomplishment',
               existing_type=mysql.JSON(),
               type_=sa.Text(),
               nullable=False)
        batch_op.alter_column('actual_time_description',
               existing_type=mysql.JSON(),
               type_=sa.Text(),
               nullable=False)
        batch_op.alter_column('actual_modification',
               existing_type=mysql.JSON(),
               type_=sa.Text(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sub_tasks', schema=None) as batch_op:
        batch_op.alter_column('actual_modification',
               existing_type=sa.Text(),
               type_=mysql.JSON(),
               nullable=True)
        batch_op.alter_column('actual_time_description',
               existing_type=sa.Text(),
               type_=mysql.JSON(),
               nullable=True)
        batch_op.alter_column('actual_accomplishment',
               existing_type=sa.Text(),
               type_=mysql.JSON(),
               nullable=True)
        batch_op.alter_column('target_modification',
               existing_type=sa.Text(),
               type_=mysql.JSON(),
               nullable=True)
        batch_op.drop_column('actual_modification_value')
        batch_op.drop_column('actual_time_description_value')
        batch_op.drop_column('actual_accomplishment_value')
        batch_op.drop_column('target_modification_value')
        batch_op.drop_column('target_time_description_value')

    # ### end Alembic commands ###
