"""added status to category

Revision ID: c81cd0e780ed
Revises: 2c63309e3bcb
Create Date: 2025-09-16 11:53:03.720710

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c81cd0e780ed'
down_revision = '2c63309e3bcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('main_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modifications_done', sa.Integer(), nullable=False))
        batch_op.drop_column('modifications')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('main_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modifications', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('modifications_done')

    # ### end Alembic commands ###
