"""empty message

Revision ID: c81fdd950893
Revises: e46047f52d86
Create Date: 2026-02-28 14:52:27.402389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c81fdd950893'
down_revision = 'e46047f52d86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opcr_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mfo', sa.Text(), nullable=True),
    sa.Column('opcr_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('efficiency', sa.Integer(), nullable=True),
    sa.Column('timeliness', sa.Integer(), nullable=True),
    sa.Column('average', sa.Integer(), nullable=True),
    sa.Column('period', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['opcr_id'], ['opcr.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('opcr_ratings')
    # ### end Alembic commands ###
