"""hehe

Revision ID: d0391836a95e
Revises: d549485e59a9
Create Date: 2025-10-23 11:31:04.481159

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd0391836a95e'
down_revision = 'd549485e59a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ipcr', schema=None) as batch_op:
        batch_op.drop_column('form_status')

    with op.batch_alter_table('opcr', schema=None) as batch_op:
        batch_op.drop_column('form_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opcr', schema=None) as batch_op:
        batch_op.add_column(sa.Column('form_status', mysql.ENUM('pending', 'reviewed', 'approved'), nullable=True))

    with op.batch_alter_table('ipcr', schema=None) as batch_op:
        batch_op.add_column(sa.Column('form_status', mysql.ENUM('pending', 'reviewed', 'approved'), nullable=True))

    # ### end Alembic commands ###
