"""added more columns in logs

Revision ID: d15c454f528f
Revises: 12b439374d98
Create Date: 2025-09-23 11:44:35.921873

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd15c454f528f'
down_revision = '12b439374d98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outputs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('main_task_id', sa.Integer(), nullable=True),
    sa.Column('sub_task_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['main_task_id'], ['main_tasks.id'], ),
    sa.ForeignKeyConstraint(['sub_task_id'], ['sub_tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('output')
    with op.batch_alter_table('sub_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('output_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['output_id'])
        batch_op.create_foreign_key(None, 'outputs', ['output_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sub_tasks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('output_id')

    op.create_table('output',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('main_task_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sub_task_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['main_task_id'], ['main_tasks.id'], name=op.f('output_ibfk_2')),
    sa.ForeignKeyConstraint(['sub_task_id'], ['sub_tasks.id'], name=op.f('output_ibfk_3')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('output_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('outputs')
    # ### end Alembic commands ###
