"""added more columns in logs

Revision ID: d15e3aeabc1c
Revises: 0b450f7206dc
Create Date: 2025-09-29 14:16:57.627872

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd15e3aeabc1c'
down_revision = '0b450f7206dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supporting_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ipcr_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('supporting_documents_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'ipcr', ['ipcr_id'], ['id'])
        batch_op.drop_column('ipcr')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supporting_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ipcr', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('supporting_documents_ibfk_1'), 'ipcr', ['ipcr'], ['id'])
        batch_op.drop_column('ipcr_id')

    # ### end Alembic commands ###
