"""empty message

Revision ID: d2217103a165
Revises: e9abcd21b149
Create Date: 2026-01-04 10:02:51.195427

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd2217103a165'
down_revision = 'e9abcd21b149'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assigned_departments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity_formula', mysql.JSON(), nullable=True))
        batch_op.add_column(sa.Column('efficiency_formula', mysql.JSON(), nullable=True))
        batch_op.add_column(sa.Column('timeliness_formula', mysql.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assigned_departments', schema=None) as batch_op:
        batch_op.drop_column('timeliness_formula')
        batch_op.drop_column('efficiency_formula')
        batch_op.drop_column('quantity_formula')

    # ### end Alembic commands ###
