"""empty message

Revision ID: d3d4da5be40f
Revises: 8170c8a6d2df
Create Date: 2026-04-17 22:35:01.758378

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd3d4da5be40f'
down_revision = '8170c8a6d2df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('main_tasks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_main_tasks_form_template_id'), type_='foreignkey')
        batch_op.drop_column('form_template_id')

    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('system_settings_ibfk_1'), type_='foreignkey')
        batch_op.drop_column('main_form_template_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('main_form_template_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('system_settings_ibfk_1'), 'form_templates', ['main_form_template_id'], ['id'])

    with op.batch_alter_table('main_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('form_template_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_main_tasks_form_template_id'), 'form_templates', ['form_template_id'], ['id'])

    # ### end Alembic commands ###
