"""added more columns in logs

Revision ID: dc8548bdcb77
Revises: 24c89c4c343a
Create Date: 2025-09-26 15:45:14.392615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc8548bdcb77'
down_revision = '24c89c4c343a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outputs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ipcr_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'ipcr', ['ipcr_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outputs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('ipcr_id')

    # ### end Alembic commands ###
