"""empty message

Revision ID: de50f8e4156f
Revises: eaae7a60c087
Create Date: 2025-10-23 21:44:43.578486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de50f8e4156f'
down_revision = 'eaae7a60c087'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ipcr', schema=None) as batch_op:
        batch_op.add_column(sa.Column('form_status', sa.Text(), nullable=True))

    with op.batch_alter_table('opcr', schema=None) as batch_op:
        batch_op.add_column(sa.Column('form_status', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opcr', schema=None) as batch_op:
        batch_op.drop_column('form_status')

    with op.batch_alter_table('ipcr', schema=None) as batch_op:
        batch_op.drop_column('form_status')

    # ### end Alembic commands ###
