"""empty message

Revision ID: e9abcd21b149
Revises: fbf27731b813
Create Date: 2025-12-28 09:52:32.502485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9abcd21b149'
down_revision = 'fbf27731b813'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assigned_departments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_weight', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assigned_departments', schema=None) as batch_op:
        batch_op.drop_column('task_weight')

    # ### end Alembic commands ###
