"""empty message

Revision ID: eb8eba6e7ce7
Revises: 6f0d2d04d52f
Create Date: 2026-04-17 18:53:10.134484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb8eba6e7ce7'
down_revision = '6f0d2d04d52f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('main_form_template_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'form_templates', ['main_form_template_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('main_form_template_id')

    # ### end Alembic commands ###
