"""added more columns in logs

Revision ID: ef95242ae3c5
Revises: d15c454f528f
Create Date: 2025-09-23 11:48:36.323577

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ef95242ae3c5'
down_revision = 'd15c454f528f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outputs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('outputs_ibfk_2'), type_='foreignkey')
        batch_op.drop_column('sub_task_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outputs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sub_task_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('outputs_ibfk_2'), 'sub_tasks', ['sub_task_id'], ['id'])

    # ### end Alembic commands ###
