"""empty message

Revision ID: fbf27731b813
Revises: 70cb4a977a8c
Create Date: 2025-12-27 20:53:24.606338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbf27731b813'
down_revision = '70cb4a977a8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('main_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('main_tasks', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
