"""empty message

Revision ID: fca61dcced86
Revises: 29a00363c7c9
Create Date: 2025-12-02 12:02:21.325887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fca61dcced86'
down_revision = '29a00363c7c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assigned_pcrs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('period', sa.String(length=100), nullable=True))

    with op.batch_alter_table('assigned_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('period', sa.String(length=100), nullable=True))

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('period', sa.String(length=100), nullable=True))

    with op.batch_alter_table('ipcr', schema=None) as batch_op:
        batch_op.add_column(sa.Column('period', sa.String(length=100), nullable=True))

    with op.batch_alter_table('main_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('period', sa.String(length=100), nullable=True))

    with op.batch_alter_table('opcr', schema=None) as batch_op:
        batch_op.add_column(sa.Column('period', sa.String(length=100), nullable=True))

    with op.batch_alter_table('opcr_ratings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('period', sa.String(length=100), nullable=True))

    with op.batch_alter_table('opcr_supporting_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('period', sa.String(length=100), nullable=True))

    with op.batch_alter_table('outputs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('period', sa.String(length=100), nullable=True))

    with op.batch_alter_table('sub_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('period', sa.String(length=100), nullable=True))

    with op.batch_alter_table('supporting_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('period', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supporting_documents', schema=None) as batch_op:
        batch_op.drop_column('period')

    with op.batch_alter_table('sub_tasks', schema=None) as batch_op:
        batch_op.drop_column('period')

    with op.batch_alter_table('outputs', schema=None) as batch_op:
        batch_op.drop_column('period')

    with op.batch_alter_table('opcr_supporting_documents', schema=None) as batch_op:
        batch_op.drop_column('period')

    with op.batch_alter_table('opcr_ratings', schema=None) as batch_op:
        batch_op.drop_column('period')

    with op.batch_alter_table('opcr', schema=None) as batch_op:
        batch_op.drop_column('period')

    with op.batch_alter_table('main_tasks', schema=None) as batch_op:
        batch_op.drop_column('period')

    with op.batch_alter_table('ipcr', schema=None) as batch_op:
        batch_op.drop_column('period')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('period')

    with op.batch_alter_table('assigned_tasks', schema=None) as batch_op:
        batch_op.drop_column('period')

    with op.batch_alter_table('assigned_pcrs', schema=None) as batch_op:
        batch_op.drop_column('period')

    # ### end Alembic commands ###
